Integration tests: Various improvements and fixes
- Speed up docker build.
- Upgrade sbcl in test container to 2.2.7. This builds sbcl from
  source which slows down the image build significantly, but is
  necessary to run the integration tests.
- Detect stumpwm crashes during tests and mark the test as failed.
- Refactor and lint script.
- Fix Makefile: Use `find' instead of `git ls-files' so that
  dependencies reflect the workdir.
- Improve test generation:
  - Refactor to keep track of a lower bound of frame sizes instead of
    number of splits.
  - Add a no-op test to toggle mode-line twice.
  - Add fragments to toggle frame indicator, move focus, and resize
    frame.
- Add stumpwm init file:
  - Abort on error.
  - Increase the duration of the frame indicator to stabilize
    tests. Remove this config from test cases.
- Improve test-basic.sh and issue-1005.sh.
- Merge issue-1002-remove and issue-1002-only into one test.
- Improve comments in test cases.

diff --git a/tests/integration-tests/container-scripts/run-test b/tests/integration-tests/container-scripts/run-test
--- a/tests/integration-tests/container-scripts/run-test
+++ b/tests/integration-tests/container-scripts/run-test
@@ -6,10 +6,13 @@ results="testcases/${testname}.results"
 rm -rf "$results"
 mkdir -p "$results"
 cd "$results"
-if "../${testname}.sh" > stdout.txt 2> stderr.txt; then
+set +e
+"../${testname}.sh" > stdout.txt 2> stderr.txt
+ec="$?"
+set -e
+if [ "$ec" == 0 ] && ! [ -e fail ]; then
     touch success
 else
-    msg="Test $testname exited with error code $?"
-    echo "$msg" > fail
+    echo "Test $testname exited with error code $ec" >> fail
     exit 1
 fi
diff --git a/tests/integration-tests/container-scripts/start-stumpwm b/tests/integration-tests/container-scripts/start-stumpwm
--- a/tests/integration-tests/container-scripts/start-stumpwm
+++ b/tests/integration-tests/container-scripts/start-stumpwm
@@ -1,5 +1,13 @@
 #!/bin/bash
 set -e
 
-stumpwm &
+(
+    set +e
+    stumpwm > stumpwm.stdout.txt 2> stumpwm.stderr.txt
+    ec="$?"
+    set -e
+    if [ "$ec" != 0 ]; then
+        echo "stumpwm exited with code $ec" >> "fail"
+    fi
+) &
 sleep 1 # Wait for stumpwm to start
